version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/ads-async
    - secure: "BUGZiWexzaLBOQIZWO7mWxRqifpxZnYxM/+UtZH6EGjv3NQtQn6WolC+41s64SgOoj6tCivOlhO75aOYQ/aBQZrpX47ZOv+aYVrWK1+8F0X8wpJ6IXoutUW7VHHG0zyBV4X9uJhJMKpGviIxaA187fEvaQi7ovzgQYLet/oTeTPt+Odu2Ayi31pX9FDrqbdxrTME8N/+WxQSq6s6q1m76RJ4oIIwvIG/JUPNeF/jFI4vECzvVoF6HrJ4dtKa7iJq26biG3Ul2ppExOXvwcvwgqt636eV6+dJUF6MA+IPC1sUR5QdTgReilCQE2RpSybzoOCEtOxEdl2w4RdDGLsIqYcJzS8E2wILOaGHHR+mBRB8C92o8JySkyafVBT8ebfqOV2pdXTzIWwDvFIOnrwlUCT6tjotLdjo6pwtZZ0fzbEHLpaYS6g1ZKwAoN6Hlq5C2W5e4YJ3C8zvqeklRa3zJzKlRczsnuD9lExFQinXtbiSb24Zlug6OUVadwuXMpjXVjsDsuRmz5cUyqyS61gItE01ZlcGFLHNHknwjLdk3XYSUsSdYYnORYs7V3dDityfVBICuwdSGRfA3SdJWhawwCST6PTPoyfQSJgZT30WcN0+H+LmPSpqSgXhJcBk3QbUm2faqUGc0fw6IdCbstUh4G+db5hrhVKHQaKcfqG5wvg="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="ads_async"

    # The name of the conda package
    - CONDA_PACKAGE="ads-async"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"



# Uncomment this block if you would like to make PIP test an allowed failure
#jobs:
#  allow_failures:
#    # This makes the PIP based Python 3.6 optional for passing.
#    # Remove this block if passing tests with PIP is mandatory for your
#    # package
#    - name: "Python 3.6 - PIP"

import:

  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml

# If not using the standard-python-conda above please uncomment the required
# (language, os, dist and stages) and optional (import statements) entries from
# the blocks below.
#
#language: python
#os: linux
#dist: xenial
#
#stages:
#  - build
#  - test
#  - name: deploy
#    if: (branch = master OR tag IS present) AND type != pull_request
#
#import:
#  # Build Stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-build.yml
#  # Tests Stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-pip.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-conda.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-linter.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/docs-build.yml
#  # Deploy Stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/pypi-upload.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/doctr-upload.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml
